# Generated by Django 6.0.1 on 2026-01-17 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaksha_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='easiness_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='concept',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concept',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='concept',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
    ]
